baseURL = 'https://ognard.com'
languageCode = 'en-us'
title = 'ognard'

theme = 'cactus'

googleAnalytics = "G-1LZTT6FJTK"

[params]
	colortheme = "dark"
	description = "Hi, I’m Bojan — an IT enthusiast and aspiring Security Analyst. This is my blog where I share everything I’m learning on my journey. Currently learning: THM Cyber Defense path & AWS Solution Architect. I’m looking to expand my experience and am open to roles in IT, Security (Analyst), or Cloud-related fields."
	mainSection = "posts"
	mainSectionTitle = "posts"
	projectsSectionTitle = "side projects"
	certsSectionTitle = "achievements & certs"
	showAllPostsOnHomePage = false
	postsOnHomePage = 10
	rss = true
	css = ["css/custom.css"]


[[params.social]]
	name = "github"
	link = "https://github.com/ognard"

[[params.social]]
	name = "linkedin"
	link = "https://linkedin.com/in/drangovski"

[[params.social]]
	name = "web"
	link = "https://drangovski.com" 

[[params.social]]
	name = "thm"
	link = "https://tryhackme.com/p/ognard" 

[[params.social]]
	name = "email"
	link = "mailto:bojandrango@gmail.com" 



[[menu.main]]
name = "~"
url = "/"
weight = 1

[[menu.main]]
name = "~/posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "whoami"
url = "/whoami"
weight = 3

